### PR TITLE
Feat/integrate minio with django

### PR DESCRIPTION
**Pull request by async-jpx**
This Pr:
- sets Minio with django-storages as default storage

### CODE REVIEW

**Review by hmoumani — APPROVED** [review]

**Review by Hattaki-Hajar — APPROVED** [review]
good job

**Review by hmoumani — CHANGES_REQUESTED** [review]
remove this shit

**Review by hmoumani — CHANGES_REQUESTED** [review]
Rebase

**Review by hmoumani — APPROVED** [review]

**Comment by hmoumani** [comment]
Most fucked up pr history

**Pull request merged**
